site_name: MECH & Cheese Programming Documentation
# site_url: https://jaegernauts5103.github.io/programming-documentation/

theme:
  name: material
  features:
    - navigation.instant
    # - navigation.top
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.tracking
    - navigation.footer
  palette:
    - scheme: default
      primary: 'F0502A'
      accent: 'F0502A'
  language: en
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - FRC:
      - Drivetrain: frc/drivetrain.md
      - Sensors: frc/sensors.md
  - BEST:
      - Controls: best/controls.md
  - Resources: resources/links.md
